/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as TermsRouteImport } from './routes/terms'
import { Route as StatusRouteImport } from './routes/status'
import { Route as SettingsRouteImport } from './routes/settings'
import { Route as ResourcesRouteImport } from './routes/resources'
import { Route as PromptsRouteImport } from './routes/prompts'
import { Route as ProfileRouteImport } from './routes/profile'
import { Route as HelpRouteImport } from './routes/help'
import { Route as DocsRouteImport } from './routes/docs'
import { Route as BuilderRouteImport } from './routes/builder'
import { Route as IndexRouteImport } from './routes/index'
import { Route as SettingsIndexRouteImport } from './routes/settings.index'
import { Route as BuilderIndexRouteImport } from './routes/builder.index'
import { Route as SettingsWorkspaceRouteImport } from './routes/settings.workspace'
import { Route as SettingsTemplatesRouteImport } from './routes/settings.templates'
import { Route as SettingsSkillsRouteImport } from './routes/settings.skills'
import { Route as SettingsSecurityCenterRouteImport } from './routes/settings.security-center'
import { Route as SettingsProjectRouteImport } from './routes/settings.project'
import { Route as SettingsPrivacyRouteImport } from './routes/settings.privacy'
import { Route as SettingsPeopleRouteImport } from './routes/settings.people'
import { Route as SettingsKnowledgeRouteImport } from './routes/settings.knowledge'
import { Route as SettingsGitRouteImport } from './routes/settings.git'
import { Route as SettingsDomainsRouteImport } from './routes/settings.domains'
import { Route as SettingsDesignSystemsRouteImport } from './routes/settings.design-systems'
import { Route as SettingsCloudRouteImport } from './routes/settings.cloud'
import { Route as SettingsBillingRouteImport } from './routes/settings.billing'
import { Route as SettingsAuditLogsRouteImport } from './routes/settings.audit-logs'
import { Route as SettingsAppsRouteImport } from './routes/settings.apps'
import { Route as SettingsAccountRouteImport } from './routes/settings.account'
import { Route as BuilderIdRouteImport } from './routes/builder.$id'

const TermsRoute = TermsRouteImport.update({
  id: '/terms',
  path: '/terms',
  getParentRoute: () => rootRouteImport,
} as any)
const StatusRoute = StatusRouteImport.update({
  id: '/status',
  path: '/status',
  getParentRoute: () => rootRouteImport,
} as any)
const SettingsRoute = SettingsRouteImport.update({
  id: '/settings',
  path: '/settings',
  getParentRoute: () => rootRouteImport,
} as any)
const ResourcesRoute = ResourcesRouteImport.update({
  id: '/resources',
  path: '/resources',
  getParentRoute: () => rootRouteImport,
} as any)
const PromptsRoute = PromptsRouteImport.update({
  id: '/prompts',
  path: '/prompts',
  getParentRoute: () => rootRouteImport,
} as any)
const ProfileRoute = ProfileRouteImport.update({
  id: '/profile',
  path: '/profile',
  getParentRoute: () => rootRouteImport,
} as any)
const HelpRoute = HelpRouteImport.update({
  id: '/help',
  path: '/help',
  getParentRoute: () => rootRouteImport,
} as any)
const DocsRoute = DocsRouteImport.update({
  id: '/docs',
  path: '/docs',
  getParentRoute: () => rootRouteImport,
} as any)
const BuilderRoute = BuilderRouteImport.update({
  id: '/builder',
  path: '/builder',
  getParentRoute: () => rootRouteImport,
} as any)
const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const SettingsIndexRoute = SettingsIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => SettingsRoute,
} as any)
const BuilderIndexRoute = BuilderIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => BuilderRoute,
} as any)
const SettingsWorkspaceRoute = SettingsWorkspaceRouteImport.update({
  id: '/workspace',
  path: '/workspace',
  getParentRoute: () => SettingsRoute,
} as any)
const SettingsTemplatesRoute = SettingsTemplatesRouteImport.update({
  id: '/templates',
  path: '/templates',
  getParentRoute: () => SettingsRoute,
} as any)
const SettingsSkillsRoute = SettingsSkillsRouteImport.update({
  id: '/skills',
  path: '/skills',
  getParentRoute: () => SettingsRoute,
} as any)
const SettingsSecurityCenterRoute = SettingsSecurityCenterRouteImport.update({
  id: '/security-center',
  path: '/security-center',
  getParentRoute: () => SettingsRoute,
} as any)
const SettingsProjectRoute = SettingsProjectRouteImport.update({
  id: '/project',
  path: '/project',
  getParentRoute: () => SettingsRoute,
} as any)
const SettingsPrivacyRoute = SettingsPrivacyRouteImport.update({
  id: '/privacy',
  path: '/privacy',
  getParentRoute: () => SettingsRoute,
} as any)
const SettingsPeopleRoute = SettingsPeopleRouteImport.update({
  id: '/people',
  path: '/people',
  getParentRoute: () => SettingsRoute,
} as any)
const SettingsKnowledgeRoute = SettingsKnowledgeRouteImport.update({
  id: '/knowledge',
  path: '/knowledge',
  getParentRoute: () => SettingsRoute,
} as any)
const SettingsGitRoute = SettingsGitRouteImport.update({
  id: '/git',
  path: '/git',
  getParentRoute: () => SettingsRoute,
} as any)
const SettingsDomainsRoute = SettingsDomainsRouteImport.update({
  id: '/domains',
  path: '/domains',
  getParentRoute: () => SettingsRoute,
} as any)
const SettingsDesignSystemsRoute = SettingsDesignSystemsRouteImport.update({
  id: '/design-systems',
  path: '/design-systems',
  getParentRoute: () => SettingsRoute,
} as any)
const SettingsCloudRoute = SettingsCloudRouteImport.update({
  id: '/cloud',
  path: '/cloud',
  getParentRoute: () => SettingsRoute,
} as any)
const SettingsBillingRoute = SettingsBillingRouteImport.update({
  id: '/billing',
  path: '/billing',
  getParentRoute: () => SettingsRoute,
} as any)
const SettingsAuditLogsRoute = SettingsAuditLogsRouteImport.update({
  id: '/audit-logs',
  path: '/audit-logs',
  getParentRoute: () => SettingsRoute,
} as any)
const SettingsAppsRoute = SettingsAppsRouteImport.update({
  id: '/apps',
  path: '/apps',
  getParentRoute: () => SettingsRoute,
} as any)
const SettingsAccountRoute = SettingsAccountRouteImport.update({
  id: '/account',
  path: '/account',
  getParentRoute: () => SettingsRoute,
} as any)
const BuilderIdRoute = BuilderIdRouteImport.update({
  id: '/$id',
  path: '/$id',
  getParentRoute: () => BuilderRoute,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/builder': typeof BuilderRouteWithChildren
  '/docs': typeof DocsRoute
  '/help': typeof HelpRoute
  '/profile': typeof ProfileRoute
  '/prompts': typeof PromptsRoute
  '/resources': typeof ResourcesRoute
  '/settings': typeof SettingsRouteWithChildren
  '/status': typeof StatusRoute
  '/terms': typeof TermsRoute
  '/builder/$id': typeof BuilderIdRoute
  '/settings/account': typeof SettingsAccountRoute
  '/settings/apps': typeof SettingsAppsRoute
  '/settings/audit-logs': typeof SettingsAuditLogsRoute
  '/settings/billing': typeof SettingsBillingRoute
  '/settings/cloud': typeof SettingsCloudRoute
  '/settings/design-systems': typeof SettingsDesignSystemsRoute
  '/settings/domains': typeof SettingsDomainsRoute
  '/settings/git': typeof SettingsGitRoute
  '/settings/knowledge': typeof SettingsKnowledgeRoute
  '/settings/people': typeof SettingsPeopleRoute
  '/settings/privacy': typeof SettingsPrivacyRoute
  '/settings/project': typeof SettingsProjectRoute
  '/settings/security-center': typeof SettingsSecurityCenterRoute
  '/settings/skills': typeof SettingsSkillsRoute
  '/settings/templates': typeof SettingsTemplatesRoute
  '/settings/workspace': typeof SettingsWorkspaceRoute
  '/builder/': typeof BuilderIndexRoute
  '/settings/': typeof SettingsIndexRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/docs': typeof DocsRoute
  '/help': typeof HelpRoute
  '/profile': typeof ProfileRoute
  '/prompts': typeof PromptsRoute
  '/resources': typeof ResourcesRoute
  '/status': typeof StatusRoute
  '/terms': typeof TermsRoute
  '/builder/$id': typeof BuilderIdRoute
  '/settings/account': typeof SettingsAccountRoute
  '/settings/apps': typeof SettingsAppsRoute
  '/settings/audit-logs': typeof SettingsAuditLogsRoute
  '/settings/billing': typeof SettingsBillingRoute
  '/settings/cloud': typeof SettingsCloudRoute
  '/settings/design-systems': typeof SettingsDesignSystemsRoute
  '/settings/domains': typeof SettingsDomainsRoute
  '/settings/git': typeof SettingsGitRoute
  '/settings/knowledge': typeof SettingsKnowledgeRoute
  '/settings/people': typeof SettingsPeopleRoute
  '/settings/privacy': typeof SettingsPrivacyRoute
  '/settings/project': typeof SettingsProjectRoute
  '/settings/security-center': typeof SettingsSecurityCenterRoute
  '/settings/skills': typeof SettingsSkillsRoute
  '/settings/templates': typeof SettingsTemplatesRoute
  '/settings/workspace': typeof SettingsWorkspaceRoute
  '/builder': typeof BuilderIndexRoute
  '/settings': typeof SettingsIndexRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/builder': typeof BuilderRouteWithChildren
  '/docs': typeof DocsRoute
  '/help': typeof HelpRoute
  '/profile': typeof ProfileRoute
  '/prompts': typeof PromptsRoute
  '/resources': typeof ResourcesRoute
  '/settings': typeof SettingsRouteWithChildren
  '/status': typeof StatusRoute
  '/terms': typeof TermsRoute
  '/builder/$id': typeof BuilderIdRoute
  '/settings/account': typeof SettingsAccountRoute
  '/settings/apps': typeof SettingsAppsRoute
  '/settings/audit-logs': typeof SettingsAuditLogsRoute
  '/settings/billing': typeof SettingsBillingRoute
  '/settings/cloud': typeof SettingsCloudRoute
  '/settings/design-systems': typeof SettingsDesignSystemsRoute
  '/settings/domains': typeof SettingsDomainsRoute
  '/settings/git': typeof SettingsGitRoute
  '/settings/knowledge': typeof SettingsKnowledgeRoute
  '/settings/people': typeof SettingsPeopleRoute
  '/settings/privacy': typeof SettingsPrivacyRoute
  '/settings/project': typeof SettingsProjectRoute
  '/settings/security-center': typeof SettingsSecurityCenterRoute
  '/settings/skills': typeof SettingsSkillsRoute
  '/settings/templates': typeof SettingsTemplatesRoute
  '/settings/workspace': typeof SettingsWorkspaceRoute
  '/builder/': typeof BuilderIndexRoute
  '/settings/': typeof SettingsIndexRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/builder'
    | '/docs'
    | '/help'
    | '/profile'
    | '/prompts'
    | '/resources'
    | '/settings'
    | '/status'
    | '/terms'
    | '/builder/$id'
    | '/settings/account'
    | '/settings/apps'
    | '/settings/audit-logs'
    | '/settings/billing'
    | '/settings/cloud'
    | '/settings/design-systems'
    | '/settings/domains'
    | '/settings/git'
    | '/settings/knowledge'
    | '/settings/people'
    | '/settings/privacy'
    | '/settings/project'
    | '/settings/security-center'
    | '/settings/skills'
    | '/settings/templates'
    | '/settings/workspace'
    | '/builder/'
    | '/settings/'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/docs'
    | '/help'
    | '/profile'
    | '/prompts'
    | '/resources'
    | '/status'
    | '/terms'
    | '/builder/$id'
    | '/settings/account'
    | '/settings/apps'
    | '/settings/audit-logs'
    | '/settings/billing'
    | '/settings/cloud'
    | '/settings/design-systems'
    | '/settings/domains'
    | '/settings/git'
    | '/settings/knowledge'
    | '/settings/people'
    | '/settings/privacy'
    | '/settings/project'
    | '/settings/security-center'
    | '/settings/skills'
    | '/settings/templates'
    | '/settings/workspace'
    | '/builder'
    | '/settings'
  id:
    | '__root__'
    | '/'
    | '/builder'
    | '/docs'
    | '/help'
    | '/profile'
    | '/prompts'
    | '/resources'
    | '/settings'
    | '/status'
    | '/terms'
    | '/builder/$id'
    | '/settings/account'
    | '/settings/apps'
    | '/settings/audit-logs'
    | '/settings/billing'
    | '/settings/cloud'
    | '/settings/design-systems'
    | '/settings/domains'
    | '/settings/git'
    | '/settings/knowledge'
    | '/settings/people'
    | '/settings/privacy'
    | '/settings/project'
    | '/settings/security-center'
    | '/settings/skills'
    | '/settings/templates'
    | '/settings/workspace'
    | '/builder/'
    | '/settings/'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  BuilderRoute: typeof BuilderRouteWithChildren
  DocsRoute: typeof DocsRoute
  HelpRoute: typeof HelpRoute
  ProfileRoute: typeof ProfileRoute
  PromptsRoute: typeof PromptsRoute
  ResourcesRoute: typeof ResourcesRoute
  SettingsRoute: typeof SettingsRouteWithChildren
  StatusRoute: typeof StatusRoute
  TermsRoute: typeof TermsRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/terms': {
      id: '/terms'
      path: '/terms'
      fullPath: '/terms'
      preLoaderRoute: typeof TermsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/status': {
      id: '/status'
      path: '/status'
      fullPath: '/status'
      preLoaderRoute: typeof StatusRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/settings': {
      id: '/settings'
      path: '/settings'
      fullPath: '/settings'
      preLoaderRoute: typeof SettingsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/resources': {
      id: '/resources'
      path: '/resources'
      fullPath: '/resources'
      preLoaderRoute: typeof ResourcesRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/prompts': {
      id: '/prompts'
      path: '/prompts'
      fullPath: '/prompts'
      preLoaderRoute: typeof PromptsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/profile': {
      id: '/profile'
      path: '/profile'
      fullPath: '/profile'
      preLoaderRoute: typeof ProfileRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/help': {
      id: '/help'
      path: '/help'
      fullPath: '/help'
      preLoaderRoute: typeof HelpRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/docs': {
      id: '/docs'
      path: '/docs'
      fullPath: '/docs'
      preLoaderRoute: typeof DocsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/builder': {
      id: '/builder'
      path: '/builder'
      fullPath: '/builder'
      preLoaderRoute: typeof BuilderRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/settings/': {
      id: '/settings/'
      path: '/'
      fullPath: '/settings/'
      preLoaderRoute: typeof SettingsIndexRouteImport
      parentRoute: typeof SettingsRoute
    }
    '/builder/': {
      id: '/builder/'
      path: '/'
      fullPath: '/builder/'
      preLoaderRoute: typeof BuilderIndexRouteImport
      parentRoute: typeof BuilderRoute
    }
    '/settings/workspace': {
      id: '/settings/workspace'
      path: '/workspace'
      fullPath: '/settings/workspace'
      preLoaderRoute: typeof SettingsWorkspaceRouteImport
      parentRoute: typeof SettingsRoute
    }
    '/settings/templates': {
      id: '/settings/templates'
      path: '/templates'
      fullPath: '/settings/templates'
      preLoaderRoute: typeof SettingsTemplatesRouteImport
      parentRoute: typeof SettingsRoute
    }
    '/settings/skills': {
      id: '/settings/skills'
      path: '/skills'
      fullPath: '/settings/skills'
      preLoaderRoute: typeof SettingsSkillsRouteImport
      parentRoute: typeof SettingsRoute
    }
    '/settings/security-center': {
      id: '/settings/security-center'
      path: '/security-center'
      fullPath: '/settings/security-center'
      preLoaderRoute: typeof SettingsSecurityCenterRouteImport
      parentRoute: typeof SettingsRoute
    }
    '/settings/project': {
      id: '/settings/project'
      path: '/project'
      fullPath: '/settings/project'
      preLoaderRoute: typeof SettingsProjectRouteImport
      parentRoute: typeof SettingsRoute
    }
    '/settings/privacy': {
      id: '/settings/privacy'
      path: '/privacy'
      fullPath: '/settings/privacy'
      preLoaderRoute: typeof SettingsPrivacyRouteImport
      parentRoute: typeof SettingsRoute
    }
    '/settings/people': {
      id: '/settings/people'
      path: '/people'
      fullPath: '/settings/people'
      preLoaderRoute: typeof SettingsPeopleRouteImport
      parentRoute: typeof SettingsRoute
    }
    '/settings/knowledge': {
      id: '/settings/knowledge'
      path: '/knowledge'
      fullPath: '/settings/knowledge'
      preLoaderRoute: typeof SettingsKnowledgeRouteImport
      parentRoute: typeof SettingsRoute
    }
    '/settings/git': {
      id: '/settings/git'
      path: '/git'
      fullPath: '/settings/git'
      preLoaderRoute: typeof SettingsGitRouteImport
      parentRoute: typeof SettingsRoute
    }
    '/settings/domains': {
      id: '/settings/domains'
      path: '/domains'
      fullPath: '/settings/domains'
      preLoaderRoute: typeof SettingsDomainsRouteImport
      parentRoute: typeof SettingsRoute
    }
    '/settings/design-systems': {
      id: '/settings/design-systems'
      path: '/design-systems'
      fullPath: '/settings/design-systems'
      preLoaderRoute: typeof SettingsDesignSystemsRouteImport
      parentRoute: typeof SettingsRoute
    }
    '/settings/cloud': {
      id: '/settings/cloud'
      path: '/cloud'
      fullPath: '/settings/cloud'
      preLoaderRoute: typeof SettingsCloudRouteImport
      parentRoute: typeof SettingsRoute
    }
    '/settings/billing': {
      id: '/settings/billing'
      path: '/billing'
      fullPath: '/settings/billing'
      preLoaderRoute: typeof SettingsBillingRouteImport
      parentRoute: typeof SettingsRoute
    }
    '/settings/audit-logs': {
      id: '/settings/audit-logs'
      path: '/audit-logs'
      fullPath: '/settings/audit-logs'
      preLoaderRoute: typeof SettingsAuditLogsRouteImport
      parentRoute: typeof SettingsRoute
    }
    '/settings/apps': {
      id: '/settings/apps'
      path: '/apps'
      fullPath: '/settings/apps'
      preLoaderRoute: typeof SettingsAppsRouteImport
      parentRoute: typeof SettingsRoute
    }
    '/settings/account': {
      id: '/settings/account'
      path: '/account'
      fullPath: '/settings/account'
      preLoaderRoute: typeof SettingsAccountRouteImport
      parentRoute: typeof SettingsRoute
    }
    '/builder/$id': {
      id: '/builder/$id'
      path: '/$id'
      fullPath: '/builder/$id'
      preLoaderRoute: typeof BuilderIdRouteImport
      parentRoute: typeof BuilderRoute
    }
  }
}

interface BuilderRouteChildren {
  BuilderIdRoute: typeof BuilderIdRoute
  BuilderIndexRoute: typeof BuilderIndexRoute
}

const BuilderRouteChildren: BuilderRouteChildren = {
  BuilderIdRoute: BuilderIdRoute,
  BuilderIndexRoute: BuilderIndexRoute,
}

const BuilderRouteWithChildren =
  BuilderRoute._addFileChildren(BuilderRouteChildren)

interface SettingsRouteChildren {
  SettingsAccountRoute: typeof SettingsAccountRoute
  SettingsAppsRoute: typeof SettingsAppsRoute
  SettingsAuditLogsRoute: typeof SettingsAuditLogsRoute
  SettingsBillingRoute: typeof SettingsBillingRoute
  SettingsCloudRoute: typeof SettingsCloudRoute
  SettingsDesignSystemsRoute: typeof SettingsDesignSystemsRoute
  SettingsDomainsRoute: typeof SettingsDomainsRoute
  SettingsGitRoute: typeof SettingsGitRoute
  SettingsKnowledgeRoute: typeof SettingsKnowledgeRoute
  SettingsPeopleRoute: typeof SettingsPeopleRoute
  SettingsPrivacyRoute: typeof SettingsPrivacyRoute
  SettingsProjectRoute: typeof SettingsProjectRoute
  SettingsSecurityCenterRoute: typeof SettingsSecurityCenterRoute
  SettingsSkillsRoute: typeof SettingsSkillsRoute
  SettingsTemplatesRoute: typeof SettingsTemplatesRoute
  SettingsWorkspaceRoute: typeof SettingsWorkspaceRoute
  SettingsIndexRoute: typeof SettingsIndexRoute
}

const SettingsRouteChildren: SettingsRouteChildren = {
  SettingsAccountRoute: SettingsAccountRoute,
  SettingsAppsRoute: SettingsAppsRoute,
  SettingsAuditLogsRoute: SettingsAuditLogsRoute,
  SettingsBillingRoute: SettingsBillingRoute,
  SettingsCloudRoute: SettingsCloudRoute,
  SettingsDesignSystemsRoute: SettingsDesignSystemsRoute,
  SettingsDomainsRoute: SettingsDomainsRoute,
  SettingsGitRoute: SettingsGitRoute,
  SettingsKnowledgeRoute: SettingsKnowledgeRoute,
  SettingsPeopleRoute: SettingsPeopleRoute,
  SettingsPrivacyRoute: SettingsPrivacyRoute,
  SettingsProjectRoute: SettingsProjectRoute,
  SettingsSecurityCenterRoute: SettingsSecurityCenterRoute,
  SettingsSkillsRoute: SettingsSkillsRoute,
  SettingsTemplatesRoute: SettingsTemplatesRoute,
  SettingsWorkspaceRoute: SettingsWorkspaceRoute,
  SettingsIndexRoute: SettingsIndexRoute,
}

const SettingsRouteWithChildren = SettingsRoute._addFileChildren(
  SettingsRouteChildren,
)

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  BuilderRoute: BuilderRouteWithChildren,
  DocsRoute: DocsRoute,
  HelpRoute: HelpRoute,
  ProfileRoute: ProfileRoute,
  PromptsRoute: PromptsRoute,
  ResourcesRoute: ResourcesRoute,
  SettingsRoute: SettingsRouteWithChildren,
  StatusRoute: StatusRoute,
  TermsRoute: TermsRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()
