package application

import (
	"sync"
	"time"
)

// ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━
//  ИСТОК АГЕНТ — Session Checkpoint Cache
//  In-memory cache for tier-based generation progress.
//  Enables resume after network disconnection.
// ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━

// SessionCheckpoint stores partial generation state per session.
type SessionCheckpoint struct {
	SessionID     string
	Specification string
	Mode          GenerationMode
	Files         map[string]string // accumulated files from completed tiers
	CompletedTier int               // last fully completed tier (-1 = none)
	TotalTiers    int               // total tier count from plan
	CreatedAt     time.Time
	UpdatedAt     time.Time
}

// SessionCache is a thread-safe in-memory store for generation checkpoints.
// Keys are session IDs (generated by frontend, passed via request).
type SessionCache struct {
	mu       sync.RWMutex
	sessions map[string]*SessionCheckpoint
	ttl      time.Duration
}

// NewSessionCache creates a cache with automatic TTL-based eviction.
func NewSessionCache(ttl time.Duration) *SessionCache {
	sc := &SessionCache{
		sessions: make(map[string]*SessionCheckpoint),
		ttl:      ttl,
	}
	go sc.evictionLoop()

	return sc
}

// Save stores or updates a checkpoint for a session.
func (sc *SessionCache) Save(cp *SessionCheckpoint) {
	sc.mu.Lock()
	defer sc.mu.Unlock()
	cp.UpdatedAt = time.Now()
	sc.sessions[cp.SessionID] = cp
}

// Get retrieves a checkpoint by session ID. Returns nil if not found or expired.
func (sc *SessionCache) Get(sessionID string) *SessionCheckpoint {
	sc.mu.RLock()
	defer sc.mu.RUnlock()
	cp, ok := sc.sessions[sessionID]
	if !ok {
		return nil
	}
	if time.Since(cp.UpdatedAt) > sc.ttl {
		return nil
	}

	return cp
}

// Delete removes a checkpoint (e.g., after successful completion).
func (sc *SessionCache) Delete(sessionID string) {
	sc.mu.Lock()
	defer sc.mu.Unlock()
	delete(sc.sessions, sessionID)
}

// evictionLoop periodically removes expired sessions.
func (sc *SessionCache) evictionLoop() {
	ticker := time.NewTicker(5 * time.Minute)
	defer ticker.Stop()
	for range ticker.C {
		sc.mu.Lock()
		now := time.Now()
		for id, cp := range sc.sessions {
			if now.Sub(cp.UpdatedAt) > sc.ttl {
				delete(sc.sessions, id)
			}
		}
		sc.mu.Unlock()
	}
}
